dist: xenial
language: python
cache: pip

matrix:
  include:
    - env: TARGET=mypy
      python: "3.7"
    - env: TARGET=pytest
      python: "3.6"
    - env: TARGET=pytest
      python: "3.7"

install:
  - travis_retry pip install poetry
  - travis_retry poetry install
script:
  - poetry run make $TARGET
