dist: xenial
language: python
cache: pip

matrix:
  include:
    - env: TARGET=flake8
      python: "3.7"
    - env: TARGET=mypy
      python: "3.7"
    - env: TARGET=pytest
      python: "3.6"
    - env: TARGET=pytest
      python: "3.7"
    - env: TARGET=pytest
      python: "3.8-dev"
    - env: TARGET=doctest
      python: "3.7"

git:
  submodules: false

before_install:
  # - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
install:
  - travis_retry pip install poetry
  - travis_retry poetry install
script:
  - poetry run make $TARGET
