dist: bionic
language: python
cache: pip

matrix:
  include:
    - env: TARGET=flake8
      python: "3.8"
    - env: TARGET=mypy
      python: "3.8"
    - env: TARGET=pytest
      python: "3.6"
    - env: TARGET=pytest
      python: "3.7"
    - env: TARGET=pytest
      python: "3.8"
    - env: TARGET=doctest
      python: "3.8"

git:
  submodules: true

before_install:
  - pip install poetry

install:
  - travis_retry poetry install -v
script:
  - poetry run make $TARGET
