---

name: Publish delb
on:
  push:
    tags: ["*"]


jobs:
  build-and-test:
    uses: ./.github/workflows/quality-checks.yml
    with:
      ref: ${{ env.GITHUB_REF_NAME }}

  upload:
    name: Publish to the cheeseshop
    if: startsWith(github.ref, 'refs/tags/')
    needs: ["build-and-test"]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/delb
    permissions:
        id-token: write
    steps:
      - name: Download package
        uses: actions/download-artifact@v4
        with:
          name: Packages
          path: dist
      - name: Upload package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

...
