---

name: Publish delb
on:  # yamllint disable-line
  push:
    tags: ["*"]


jobs:
  build-and-test:
    uses: ./.github/workflows/quality-checks.yml
    with:
      ref: ${{ env.GITHUB_REF_NAME }}

  upload:
    name: Publish to the cheeseshop
    if: startsWith(github.ref, 'refs/tags/')
    needs: ["build-and-test"]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/delb
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Download package
        uses: actions/download-artifact@v4
        with:
          name: Packages
          path: dist
      - name: Upload package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
      - name: Install dependencies for creating GH release
        run: pip install panflute pypandoc sphinx
      # TODO build docs, so that objects.inv is available
      - name: Create GH release
        run: >-
          python .github/scripts/make-github-release.py ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

...
