---

name: Publish delb
on:
  push:
    tags: ["*"]


jobs:
  build-and-test:
    uses: ./.github/workflows/quality-checks.yml
    with:
      ref: ${{ env.GITHUB_REF_NAME }}

  pypi:
    name: Publish to the cheeseshop
    needs: ["build-and-test"]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/delb
    permissions:
      id-token: write

    steps:
      - name: Download package
        uses: actions/download-artifact@v4
        with:
          name: Packages
          path: dist
      - name: Upload package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  github:
    name: Create a Github release
    needs: ["build-and-test"]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - uses: actions/setup-python@v5
        with:
          cache: pip
          python-version: 3.x
      - uses: extractions/setup-just@v2
      - run: pipx install hatch
      - run: just docs
      - run: pip install panflute pypandoc sphinx
      - run: >-
          python .github/scripts/make-github-release.py ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

...
