---

name: quality-checks

on:
  pull_request:
  push:
    branches:
      - main

jobs:

  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.7
          - 3.8
          - 3.9
          - "3.10"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - run: python -m pip install --upgrade pip setuptools wheel
      - uses: abatilo/actions-poetry@v2.1.4
      - run: poetry install
      - run: poetry run make pytest

  other-quality-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - check-formatting
          - doctest
          - mypy
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - run: python -m pip install --upgrade pip setuptools wheel
      - uses: abatilo/actions-poetry@v2.1.4
      - run: poetry install
      - run: poetry run make ${{ matrix.target }}

...
