---

name: create release

on:
  push:
    tags:
      - 'v*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: register date variable
        id: registry
        run: |
          echo "::set-output name=date::$(date '+%Y-%m-%d')"
          echo "::set-output name=tag::${GITHUB_REF#refs/*/}"
      - uses: cuchi/jinja2-action@v1.2.0
        with:
          template: .github/templates/CITATION.cff.j2
          output_file: CITATION.cff
          variables: |
            release_date=${{ steps.registry.outputs.date }}
            release_tag=${{ steps.registry.outputs.tag }}
      - uses: LutrisEng/validate-cff@v1.0.0

...
